### ISSUE TITLE
Feature: custom button positions OR custom template URLs

### ISSUE THREAD

**Issue by Arxi** [rajeshwarpatlolla/ionic-datepicker#207]
It would be cool if we could swap the position of buttons. In some app designs, the confirmation buton (i.e. "Set") is always located on the right side and the cancel button (i.e. "Close") on the left side.

This could be set via a config setting, or better yet, maybe it would be possible to pass an URL to a custom template in the config object (i.e. separate URLs for popup and modal templates). Such an approach would allow for a better customization of the template, though I understand the template would have to contain the current function calls, use the same angular variables, CSS classes and such.

**Comment by rajeshwarpatlolla** [comment]
One of the feature is same as [this](https://github.com/rajeshwarpatlolla/ionic-datepicker/issues/221).
Regarding the custom template, it will be hard to provide such feature. If the customisation goes little wrong it will make break the entire component functionality. In order to avoid such thing i have provided the CSS, so that you can customise the look and feel.
