### ISSUE TITLE
Month and year pickers are not working when running in a device

### ISSUE THREAD

**Issue by jemliF** [rajeshwarpatlolla/ionic-datepicker#208]
Hi, Thank you for this great plugin.
Actually, it works fine in the browser, but when i tried it in a device using the Ionic View App, both year and month pickers are not working: see this photo https://drive.google.com/file/d/0B2S5amMpeE6QSlR6UTE4XzI1Unc/view?usp=sharing

**Comment by Arxi** [comment]
I encountered this issue on a device with a browser that doesn't fully support CSS Flexbox. In my case, it was Android 4.3 browser (see [here](http://caniuse.com/#search=flex)).

I guess this is because ionic-datepicker uses [Ionic's grid system](http://ionicframework.com/docs/components/#grid) based on flex. I currently see no other solution than to style the `col-` CSS classes on my own.

**Comment by jemliF** [comment]
Can you please tell me what you did to fix that issue

**Comment by kaqfa** [comment]
I face the same problem, hopefully someone address us how to solve that.

**Comment by jemliF** [comment]
@kaqfa it seems that it's not working with android version < 4.4

**Comment by rainke** [comment]
I face this problem in firefox brower(android mobile)

**Comment by rajeshwarpatlolla** [comment]
Please take a look at the latest version [v1.2.0](https://github.com/rajeshwarpatlolla/ionic-datepicker/releases/tag/v1.2.0)
