### ISSUE TITLE
Hide today button 

### ISSUE THREAD

**Issue by prakashsejwani** [rajeshwarpatlolla/ionic-datepicker#81]
Hi @rajeshwarpatlolla ,
I'm using this plugin in my ionic project, and i would like to have one feature like hiding or removing today button, In fact i found somebody has already implemented this feature by forking your project, here is the link https://github.com/Diones/ionic-datepicker
But this project is running behind 105 commits, so is it possible to implement same functionality in this plugin also.

**Comment by rajeshwarpatlolla** [comment]
Today button was a mandatory button which most of the people asked me to implement.

**Comment by gruming** [comment]
1+

**Comment by rajeshwarpatlolla** [comment]
Thanks for your suggestion @prakashsejwani.

**Comment by prakashsejwani** [comment]
:thumbsup:

**Comment by aaronprojects** [comment]
+1

**Comment by prakashsejwani** [comment]
Hey @rajeshwarpatlolla  any update, looking forward eagerly.

**Comment by rajeshwarpatlolla** [comment]
I am trying my best to get some time out of busy my schedule. It won't take much time in implementing the functionality, you suggested. But there are few other fixes i need to work. So meanwhile if you can make a PR, that would be really nice, if you don't get some time to make a PR, give me some time, so that i can work on this as well as few other issues and i can make a new release.

**Comment by rajeshwarpatlolla** [comment]
Please take a look at [this pull request](https://github.com/rajeshwarpatlolla/ionic-datepicker/pull/84) which is already merged. You can pull from master branch and check it out.

**Comment by prakashsejwani** [comment]
Thanks @rajeshwarpatlolla  and @satyapriya :+1:

**Comment by satyapriya** [comment]
:+1:
